### ISSUE TITLE
Metro only j2j version metadata

### ISSUE THREAD

**Issue by jodyhoonstarr** [LEDApplications/lehd-schema#18]
Clarify that [the line](https://lehd.ces.census.gov/data/schema/latest/lehd_public_use_schema.html#_version_metadata_for_qwi_j2j_and_pseo_files_version_txt) `Some J2J metadata may contain multiple lines, as necessary.` applies to metros only.

E.g. `version metadata contains only a single line for state and us geolevels but may contain multiple entries for metro` something like that.

**Comment by srt1** [comment]
Assuming that it is true that metro areas are the only ones that have multiple lines, what probably makes the most sense is to say that, and then give a sample (e.g., first few lines) as we do with the other ones. You're right, the "as necessary" is a little opaque.

Unfortunately, we probably don't have access to a sample from a vintage that would be consistent with the others - should we update them all? Not a huge issue either way, but I see the point.

**Comment by jodyhoonstarr** [comment]
Went ahead and stuck in an example of metro metadata and updated the others around it ([link](https://ledapplications.github.io/lehd-schema/lehd_public_use_schema.html#_version_metadata_for_qwi_j2j_and_pseo_files_version_txt)). Good enough I think.
