### ISSUE TITLE
Describe new J2J metadata table for "all" availability

### ISSUE THREAD

**Issue by srt1** [LEDApplications/lehd-schema#21]
The j2j "avail" tables describe the quarter ranges that each state pair may show up in the J2JOD data. Each one is state or us specific. A new output table is being added stacking all the state+us tables, called j2j_all_avail.csv. This file will be described in the schema.

**Comment by heathhayward** [comment]
That language looks good to me. Were you waiting for the file to be ready to make (link:j2j0d_all_avail.csv[]) a hyperlink in that new sentence?

**Comment by srt1** [comment]
I don't believe we normally make hyperlinks directly to the data. I just bolded it to make it look like a dataset name - or something. We probably haven't been too consistent with conventions on that kind of thing. But feel free to edit or add links, as you feel appropriate. (@heathhayward )

**Comment by heathhayward** [comment]
I have an edit to this ticket. Waiting to hear whether the file will be csv or a csv.gz...

**Comment by heathhayward** [comment]
If this commit looks ok, you can close this ticket.

**Comment by jodyhoonstarr** [comment]
looks good to me
