### ISSUE TITLE
NAICS 2022

### ISSUE THREAD

**Issue by srt1** [LEDApplications/lehd-schema#22]
Switch to 2022 NAICS codes. Some changes are required in the text. I believe that the label table will be generated from the FORMATS process, and a mechanism exists to grab it directly (?)

**Comment by srt1** [comment]
I think I am done with edits for V4.9.2, V4.10.0, including adding change notes. The main outstanding issue is adding the label_industry.csv, which hasn't been created in production yet (with the 2022 NAICS and the sector code correction). What's the best way to proceed on that?

@jodyhoonstarr @heathhayward

**Comment by jodyhoonstarr** [comment]
Is there any harm in waiting for it? That would be my preference. Or we could do a beta/release candidate version of these two schema versions.

**Comment by srt1** [comment]
We can wait on 4.10.0. We should push 4.9.2 out sooner (though we may need to update it later, after PSEO partners request changes to institution names - I'm okay with editing those in the same schema, as needed)
________________________________

**Comment by srt1** [comment]
@jodyhoonstarr @heathhayward 

I manually added the label_industry table, since I was working on the updated tables. This should be the same as the one that comes out of production. We can post this in advance, if we wish. I was wondering whether we should have some kind of user notification about upcoming 2022 codes, in any event. Will bring up question at QA meeting.

**Comment by srt1** [comment]
Note, the 2022 NAICS codes came along with a correction for the sector code. It has been changed from "2" to "S". This is consistent with ind_level.csv, as well as with the data contained on the files.
