### ISSUE TITLE
Change PSEO to 2020 dollars

### ISSUE THREAD

**Issue by srt1** [LEDApplications/lehd-schema#23]
PSEO earnings will be reported in 2020 dollars with the R2022Q4/R2023Q1 release. Edit measure text.

**Comment by andrewfoote** [comment]
Addressed this.

**Comment by srt1** [comment]
@jodyhoonstarr: 
It took me a little while to figure out what @andrewfoote did here. It looks like he forked the schema repo, which to my understanding is something like creating a clone of the repo? Reading up on it, it is also apparently done when you are starting up a basically independent project. I don't think that is what he really wanted to do.

I had previously made the same change @andrewfoote made in the branch (6ccddf9). When we are ready to close this out, please merge the change from my branch, rather than the fork. I think that is probably a better practice for what we are doing.

Thanks.

**Comment by andrewfoote** [comment]
Oh no. I am sorry @srt1 - I don't know how I did that

**Comment by jodyhoonstarr** [comment]
It's all good. That's a perfectly clean way to make changes that aren't ready to go into main yet. Basically you do whatever you want then open PR (that I just did above) to merge into this repo. I'll leave it as is and merge in once we're ready. No need to change anything.

**Comment by jodyhoonstarr** [comment]
Oh, just saw the second part of what you said. Will use your changes rather than the fork.

**Comment by srt1** [comment]
Yes - curiously, Github seems to have made the more expensive and unusual forking operation a lot more obvious than the common branching operation. Easy to fool users who are trying to do things quickly.

BTW, if there are any late-breaking changes to the institution names, I think we can continue to use the V4.9.2 branch, even after it has been published. I'm not against some minor edits/corrections.
________________________________

**Comment by jodyhoonstarr** [comment]
Merged in the 4.9.2-dev changes to main
