### ISSUE TITLE
Fix headings, drop non-existent J2J variability sections

### ISSUE THREAD

**Issue by srt1** [LEDApplications/lehd-schema#28]
There's a bunch of a mess...

**Comment by srt1** [comment]
@heathhayward 
Let me know what you think about these changes.

**Comment by heathhayward** [comment]
Looks good. My only comment is that perhaps "4.4.3. Variability Measures for QWI Rates (QWIRV) - National-level" should be "4.4.3. Variability Measures for QWI Rates (QWIRV) - National-level only" to match the above section header.

**Comment by srt1** [comment]
I had misnamed PSEO
