### ISSUE TITLE
Does not build on Ruby 2.5 (Ubuntu 20)

### ISSUE THREAD

**Issue by julfersnlt** [LEDApplications/lehd-schema#3]
The script `generate_schema_docs.sh` fails on Ruby 2.5, which is still the default on current Ubuntu.

```
$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

When running the asciidoctor command by hand:

```
$ asciidoctor -r ../lib/csvsubcolumn-include-processor.rb -a stylesheet=../lib/css/asciidoctor.css -a schemaversion=V4.8.3 -a outfilesuffix=.html -o ../dist/lehd_public_use_schema.html --trace lehd_public_use_schema.asciidoc
Traceback (most recent call last):
        ...
         2: from .../asciidoctor-2.0.17/lib/asciidoctor/reader.rb:1032:in `[]'
         1: from .../lehd-schema/lib/csvsubcolumn-include-processor/extension.rb:33:in `process'
/usr/lib/ruby/2.5.0/csv.rb:1139:in `foreach': asciidoctor: FAILED: /mnt/c/Users/Josiah Ulfers/Census/lehd-schema/lehd-schema/src/lehd_public_use_schema.asciidoc: Failed to load AsciiDoc document - wrong number of arguments (given 2, expected 1) (ArgumentError)
```

Caused by use of the mode argument which isn't present in [Ruby 2.5's CSV.foreach](https://ruby-doc.org/stdlib-2.5.1/libdoc/csv/rdoc/CSV.html#method-c-foreach)

https://github.com/LEDApplications/lehd-schema/blob/dafcaa24af88fb80d5b7195e1162f87a9cb01709/lib/csvsubcolumn-include-processor/extension.rb#L33

Since mode is an [optional argument in Ruby 3 that defaults to "r"](https://ruby-doc.org/stdlib-3.1.0/libdoc/csv/rdoc/CSV.html#method-c-foreach), it should be safe to remove.

**Comment by julfersnlt** [comment]
I can send a pull request for this

**Comment by jodyhoonstarr** [comment]
Thanks for sending these in. Will check it out today.
