### ISSUE TITLE
Old links in label_geo_level.csv

### ISSUE THREAD

**Issue by julfersnlt** [LEDApplications/lehd-schema#34]
[label_geo_level.csv](https://github.com/LEDApplications/lehd-schema/blob/main/src/label_geo_level.csv) contains these links:

* https://www.census.gov/geographies/reference-files/2017/demo/popest/2017-fips.html
* https://www.census.gov/geo/reference/ansi_statetables.html
* https://www.census.gov/geo/reference/codes/cou.html
* http://www.census.gov/population/metro/ (twice)

The last 3 are 404 not found. The process from https://github.com/LEDApplications/DEPRECATED-lehd-schema/issues/9 probably missed them because they're not rendered in the html.

The first one still loads ok, but should be updated to 2021?

**Comment by srt1** [comment]
@heathhayward/ or @jodyhoonstarr  , can you review these?

This is one of those annoying things where we technically need to edit it upstream in production, since I think it is hardcoded in the formats process. We can do that in a separate ticket, but for expediency we can manually edit these files directly in the schema.

Thanks

**Comment by srt1** [comment]
created ticket in Redmine to track this activity

https://redmine.lehd.census.gov/redmine/issues/19659

**Comment by heathhayward** [comment]
[label_geo_level.csv](https://github.com/LEDApplications/lehd-schema/files/12919905/label_geo_level.csv)

**Comment by heathhayward** [comment]
Divisions are hardcoded in the system so we are still using 2017 definitions. But I don't think they ever change. Let me know if you have edits/suggestions for the changes I've made

**Comment by srt1** [comment]
Heath's updates have been incorporated into the 2023 branch. So long as the links aren't broken, I will defer to him as to the most appropriate ones we want to present. Thanks.

**Comment by jodyhoonstarr** [comment]
I don't think we want to display these links - they're in a bit of a strange spot in terms of use case. Going from input csvs to rendered tables w/ links isn't easy in the current setup. Generally our csvs should have information that gets dumped in a plain table. If we want something formatted e.g [I'm a link to a source](www.example.com) we should probably hardcode it and not load from csv.

Gonna close this but feel free to add comments or re-open if you have other thoughts.

**Comment by srt1** [comment]
On Jody's comment, I'm not sure the what the genesis of these links in the csv's were - I'm don't think it was me. Are you suggesting they shouldn't be there at all? I really don't have much of an opinion on them.
________________________________

**Comment by heathhayward** [comment]
Let's just leave it like it is. The current setup on https://lehd.ces.census.gov/data/schema/latest/lehd_public_use_schema.html#_geography shows the 1st 3 columns of the CSV. So it renders nicely. But if a user downloads the CSV then they have more info, including the links

**Comment by jodyhoonstarr** [comment]
This is another good candidate for removing the csv and putting the data we want in as text (similar to #33). Right now the links are hidden in the CSV only. Easiest options are

1. Leave it as is, links are only in the csv
2. Remove the links from the CSV
3. Remove the csv and put all the content into a hardcoded table

I don't have a strong preference but I'm switching over to work on the other similar issue (#33) so if we wanna go with option 3 now is probably the time.

**Comment by heathhayward** [comment]
If you'd prefer to go with option 3, I'm ok with that. Since your doing the schema lifting these days, if you are ok with hardcodes then who am I to argue!

**Comment by jodyhoonstarr** [comment]
I went ahead and hardcoded a table using the data in label_geo_level and left the original csv file since it's probably used by someone in an automated way unlike the naming formats. 

This way the link checker will holler if any of those URLs break in which case we'll have to go fix the CSV and table. Since this doesn't change often it seems like the best way. Here's a [link to the table](https://ledapplications.github.io/lehd-schema/lehd_public_use_schema.html#_geographic_levels)

**Comment by heathhayward** [comment]
[label_geo_level.csv](https://github.com/LEDApplications/lehd-schema/files/13042920/label_geo_level.csv)
This one is better for 2023. Note that the links are still the same, only changes are:

- removed "2020" text from the county line 
- changed the metro delineation date to July 2023 for both CBSA lines
