### ISSUE TITLE
Update to 2023 geography

### ISSUE THREAD

**Issue by srt1** [LEDApplications/lehd-schema#36]
Will contain COGs for Connecticut

**Comment by srt1** [comment]
Setting this for a release candidate, prior to finalization

**Comment by jodyhoonstarr** [comment]
Closed by #38

**Comment by heathhayward** [comment]
this is probably the wrong spot for this, but we need to change the last sentence of the first paragraph under http://lehdweb.dev.ces.census.gov/data/schema/V4.11.0-draft/lehd_public_use_schema.html#_geography to the following:

The 2023 vintage of [Census TIGER/Line geography](https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html) is used for all tabulations as of the R2024Q1 release.
