### ISSUE TITLE
Update PSEO institution names; Earnings to 2021 (for R2024Q2-ish release)

### ISSUE THREAD

**Issue by srt1** [LEDApplications/lehd-schema#46]
1. [University of Rio Grande](https://ope.ed.gov/dapip/#/institution-profile/136747) is a hybrid institution, for which we have only the community college part at this time. The institution will be clerically edited to signify both halves (upstream the PEPS process).
2. Earnings data will be published in 2021 dollars.

**Comment by srt1** [comment]
Note: the URG CC has the number 00311601 in PEPS. We could crosswalk it to that instead of changing the label for 00311600. That would involve a GRADS fix, and some custom shenanigans in PSEO for the recirculated tables.

```
00311600,University of Rio Grande,Rio Grande,OH,I,39
00311601,University of Rio Grande - Rio Grande Community College,Rio Grande,OH,I,39
00311602,University of Rio Grande - Meigs Center,Pomeroy,OH,I,39
00311603,University of Rio Grande - Chillicothe Graduate Site,Chillicothe,OH,I,39
00311604,University of Rio Grande - Hamilton Graduate Site,Hamilton,OH,I,39
00311605,University of Rio Grande - Columbus Graduate Site,Columbus,OH,I,39
00311606,University of Rio Grande - Portsmouth Graduate Site,Portsmouth,OH,I,39
00311607,University of Rio Grande - Nelsonville,Nelsonville,OH,I,39
00311608,University of Rio Grande - Columbus Graduate Site,Columbus,OH,I,39
00311609,University of Rio Grande - Jackson Center,Jackson,OH,I,39
00311610,University of Rio Grande - McArthur Center,McArthur,OH,I,39

```

**Comment by andrewfoote** [comment]
@srt1 I think we probably would want to do a custom fix in this way. Then we don't have to change schema, only change the values which are further upstream.
And it keeps consistency. I will run a fix this week in GRADS for ODHE.

**Comment by andrewfoote** [comment]
@srt1 I fixed this upstream in GRADS, so consider the first section done. We just need to change in recirculated.

**Comment by srt1** [comment]
We will undo the schema edit to the institution names table. The OPEID has been updated in the pseo vintage.
