### ISSUE TITLE
institutions that are not attached to single states - schema edits

### ISSUE THREAD

**Issue by srt1** [LEDApplications/lehd-schema#49]

**Comment by srt1** [comment]
Online institutions with no particular state associations are expected to be added to PSEO in a release in 2024. The schema may need some recontextualization of what states or metadata files mean for this institution. Review things noted below.

pseo_[st]_institutions.csv - leave state name and FIPS blank * pseo_[st]_partners.txt - let Andrew sort that one out * version_pseo.txt - not sure what codes we want to use here... (state postal, state numeric FIPS)
could require schema edits
[geohi](https://lehd.ces.census.gov/data/schema/j2j_latest/lehd_csv_naming.html#_geohi)
[version.txt](https://lehd.ces.census.gov/data/schema/j2j_latest/lehd_public_use_schema.html#_version_metadata_for_qwi_j2j_and_pseo_files_version_txt)
Flows tables will not have any instate counts (flag 5)
[Institution metadata](https://lehd.ces.census.gov/data/schema/j2j_latest/lehd_public_use_schema.html#_version_metadata_for_qwi_j2j_and_pseo_files_version_txt) will require some edits * Probably just leave the FIPS and postal codes missing * Add some explanatory text

**Comment by srt1** [comment]
@andrewfoote @heathhayward @jodyhoonstarr

After a little review, I elected to edit  the section on [Additional Metadata for PSEO Files](https://ledapplications.github.io/lehd-schema/lehd_public_use_schema.html#_additional_metadata_for_pseo_files). I added a bullet for **Online Institutions**. Not terribly happy it is a bullet, but it's not really a subsection either. I could also imagine it being a warning box or something, like we do in the [Snapshot doc](https://lehd.ces.census.gov/data/lehd-snapshot-doc/latest/sections/introduction.html#citing-the-data) but I don't know how to do that. 

I don't know if any deeper changes to the schema would be at all helpful - I can't imagine anyone would ever come across them. They'd be pretty diligent if they find this. We might want to put a note somewhere in the release [data notices](https://lehd.ces.census.gov/doc/PSEO_data_notices.pdf)?.

Thoughts?

**Comment by heathhayward** [comment]
I think the addition of the bullet works fine. And I agree it's worth documenting in this quarter's Data Notice PDF.

**Comment by andrewfoote** [comment]
@heathhayward @srt1 I agree that we should note it in the data notices.
