### ISSUE TITLE
NAICS website has moved

### ISSUE THREAD

**Issue by julfersnlt** [LEDApplications/lehd-schema#5]
The link from https://lehd.ces.census.gov/data/schema/latest/lehd_public_use_schema.html#_industry_2 to the main naics site has moved.

> For a full listing of all valid 2017 NAICS codes, see https://www.census.gov/cgi-bin/sssd/naics/naicsrch?chart=2017.

![image](https://user-images.githubusercontent.com/86742602/149555554-6aa6d5d4-f1b2-4f30-9441-4caed1cfb09e.png)

It does redirect, but probably best to fix the link anyway. I believe the new link should be https://www.census.gov/naics/?58967?yearbck=2017

**Comment by julfersnlt** [comment]
I can send a pull request to this repository, but maybe also should be a backport to https://github.com/LEDApplications/DEPRECATED-lehd-schema?

**Comment by julfersnlt** [comment]
I copied the link in the description, https://www.census.gov/naics/?58967?yearbck=2017, from the naics landing page https://www.census.gov/naics/

![image](https://user-images.githubusercontent.com/86742602/149557533-95d51e39-6404-4a6e-9737-4d2931ab4904.png)

After visiting the landing page, clicking the link displays a table of Sectors.

![image](https://user-images.githubusercontent.com/86742602/149557600-c4fe5228-f215-4e75-b100-fdb28132e2a9.png)

When visited directly, however, the link displays the "introduction" text. I'll guess that isn't intentional and go ahead with the link that has the yearbck parameter.

**Comment by jodyhoonstarr** [comment]
Yeah, I've got that direct link behavior too. I'm not sure I trust that random number in the link - hopefully it's not some CMS generated version ID. We can always revisit.

**Comment by jodyhoonstarr** [comment]
Closed by #6
